// DATOS DE EJEMPLO
// Más adelante estos datos vendrán de tu backend (NestJS) con fetch('/api/vacantes').
// Por ahora sirven para que el front se vea igual que los mockups.

export const categorias = [
  { id: 'tecnologia', nombre: 'Tecnología y Sistemas', icono: 'laptop' },
  { id: 'administracion', nombre: 'Administración y Oficina', icono: 'pencil' },
  { id: 'ventas', nombre: 'Ventas y Comercial', icono: 'megaphone' },
  { id: 'salud', nombre: 'Salud y Bienestar', icono: 'salud' },
  { id: 'educacion', nombre: 'Educación y Formación', icono: 'educacion' },
  { id: 'manufactura', nombre: 'Manufactura y Producción', icono: 'fabrica' },
  { id: 'construccion', nombre: 'Construcción y Oficios', icono: 'casco' },
  { id: 'otros', nombre: 'Otros sectores', icono: 'mas' },
]

export const ciudades = ['Bogotá, D.C.', 'Medellín', 'Cali', 'Barranquilla']
export const lugares = ['Remoto', 'Híbrido', 'Presencial']
export const jornadas = ['Tiempo completo', 'Medio tiempo', 'Freelance']
export const contratos = ['Indefinido', 'Temporal', 'Prestación de servicios']

const beneficiosBase = [
  'Ambiente creativo y colaborativo',
  'Proyectos de alto impacto',
  'Flexibilidad y trabajo remoto',
  'Oportunidades de crecimiento',
]

export const jobs = [
  {
    id: 1,
    titulo: 'Diseñador Gráfico Senior',
    empresa: 'Creativo Studio',
    sectorEmpresa: 'Agencia de diseño y branding',
    empleados: '51 - 200 empleados',
    categoria: 'tecnologia',
    ciudad: 'Bogotá, D.C.',
    lugar: 'Remoto',
    jornada: 'Tiempo completo',
    contrato: 'Indefinido',
    salarioMin: 2500000,
    salarioMax: 4000000,
    inicial: 'C',
    color: '#0A2D6B',
    tags: ['Diseño', 'Creatividad'],
    lema: 'Ideas que se convierten en grandes marcas',
    sobreEmpresa:
      'En Creativo Studio creemos en el poder del diseño para transformar ideas en experiencias que conectan.',
    descripcion:
      'Buscamos un Diseñador Gráfico Senior con pasión por la creatividad y el diseño, que quiera hacer parte de un equipo innovador. Serás responsable de desarrollar piezas gráficas para campañas digitales y material de marca, trabajando de la mano con el equipo de marketing.',
    responsabilidades: [
      'Diseñar piezas gráficas para redes sociales, web y medios impresos.',
      'Desarrollar conceptos visuales alineados a la identidad de la marca.',
      'Colaborar con el equipo de marketing y contenido.',
      'Revisar y ajustar artes según feedback.',
    ],
    requisitos: [
      'Profesional en Diseño Gráfico, Comunicación Visual o afines.',
      'Mínimo 3 años de experiencia en diseño gráfico digital.',
      'Dominio de Adobe Photoshop, Illustrator e InDesign.',
      'Portafolio actualizado.',
      'Creatividad, proactividad y trabajo en equipo.',
    ],
    beneficios: beneficiosBase,
  },
  {
    id: 2,
    titulo: 'Diseñador Gráfico Jr.',
    empresa: 'NovaTech',
    sectorEmpresa: 'Empresa de tecnología',
    empleados: '11 - 50 empleados',
    categoria: 'tecnologia',
    ciudad: 'Bogotá, D.C.',
    lugar: 'Híbrido',
    jornada: 'Tiempo completo',
    contrato: 'Indefinido',
    salarioMin: 1500000,
    salarioMax: 2500000,
    inicial: 'N',
    color: '#0A2D6B',
    tags: ['Híbrido', 'Diseño'],
    lema: 'Tecnología que mueve ideas',
    sobreEmpresa: 'NovaTech desarrolla software para empresas que quieren crecer.',
    descripcion: 'Apoyarás al equipo de producto creando piezas visuales y prototipos.',
    responsabilidades: ['Crear piezas para redes y web.', 'Apoyar al equipo de producto.'],
    requisitos: ['Tecnólogo o estudiante de diseño.', 'Manejo de Figma.', 'Portafolio.'],
    beneficios: beneficiosBase,
  },
  {
    id: 3,
    titulo: 'Diseñador Gráfico',
    empresa: 'Brandify',
    sectorEmpresa: 'Marketing digital',
    empleados: '11 - 50 empleados',
    categoria: 'ventas',
    ciudad: 'Medellín',
    lugar: 'Presencial',
    jornada: 'Tiempo completo',
    contrato: 'Temporal',
    salarioMin: 2000000,
    salarioMax: 3000000,
    inicial: 'B',
    color: '#0F1B3D',
    tags: ['Presencial', 'Publicidad'],
    lema: 'Marcas que se recuerdan',
    sobreEmpresa: 'Brandify es una agencia de marketing digital con clientes en toda Colombia.',
    descripcion: 'Diseñarás campañas para clientes de distintos sectores.',
    responsabilidades: ['Diseñar campañas.', 'Preparar artes finales.'],
    requisitos: ['2 años de experiencia.', 'Adobe Illustrator y Photoshop.'],
    beneficios: beneficiosBase,
  },
  {
    id: 4,
    titulo: 'Diseñador Gráfico',
    empresa: 'PixelLab',
    sectorEmpresa: 'Creatividad y diseño',
    empleados: '1 - 10 empleados',
    categoria: 'tecnologia',
    ciudad: 'Cali',
    lugar: 'Híbrido',
    jornada: 'Tiempo completo',
    contrato: 'Prestación de servicios',
    salarioMin: 1800000,
    salarioMax: 2800000,
    inicial: 'P',
    color: '#6D4FD8',
    tags: ['Híbrido', 'Diseño'],
    lema: 'Pequeños detalles, grandes pantallas',
    sobreEmpresa: 'PixelLab es un estudio creativo que diseña experiencias digitales.',
    descripcion: 'Trabajarás en proyectos web y de identidad visual.',
    responsabilidades: ['Diseñar interfaces.', 'Crear identidades visuales.'],
    requisitos: ['Portafolio web.', 'Manejo de Figma y Adobe.'],
    beneficios: beneficiosBase,
  },
  {
    id: 5,
    titulo: 'Diseñador Gráfico Digital',
    empresa: 'GreenLife',
    sectorEmpresa: 'Salud y bienestar',
    empleados: '51 - 200 empleados',
    categoria: 'salud',
    ciudad: 'Barranquilla',
    lugar: 'Remoto',
    jornada: 'Tiempo completo',
    contrato: 'Indefinido',
    salarioMin: 2000000,
    salarioMax: 3500000,
    inicial: 'G',
    color: '#15803D',
    tags: ['Remoto', 'Diseño'],
    lema: 'Bienestar que se ve bien',
    sobreEmpresa: 'GreenLife promueve hábitos saludables con productos y contenido digital.',
    descripcion: 'Crearás contenido visual para redes y campañas de bienestar.',
    responsabilidades: ['Crear contenido para redes.', 'Diseñar empaques digitales.'],
    requisitos: ['Experiencia en diseño digital.', 'Conocimiento de motion graphics.'],
    beneficios: beneficiosBase,
  },
  {
    id: 6,
    titulo: 'Desarrollador Frontend',
    empresa: 'NovaTech',
    sectorEmpresa: 'Empresa de tecnología',
    empleados: '11 - 50 empleados',
    categoria: 'tecnologia',
    ciudad: 'Bogotá, D.C.',
    lugar: 'Remoto',
    jornada: 'Tiempo completo',
    contrato: 'Indefinido',
    salarioMin: 3500000,
    salarioMax: 5000000,
    inicial: 'N',
    color: '#0A2D6B',
    tags: ['Remoto', 'React'],
    lema: 'Tecnología que mueve ideas',
    sobreEmpresa: 'NovaTech desarrolla software para empresas que quieren crecer.',
    descripcion: 'Construirás interfaces con React junto al equipo de producto.',
    responsabilidades: ['Desarrollar componentes React.', 'Consumir APIs REST.'],
    requisitos: ['2 años con React.', 'Git y trabajo en equipo.'],
    beneficios: beneficiosBase,
  },
  {
    id: 7,
    titulo: 'Auxiliar de Enfermería',
    empresa: 'GreenLife',
    sectorEmpresa: 'Salud y bienestar',
    empleados: '51 - 200 empleados',
    categoria: 'salud',
    ciudad: 'Cali',
    lugar: 'Presencial',
    jornada: 'Medio tiempo',
    contrato: 'Temporal',
    salarioMin: 1800000,
    salarioMax: 2500000,
    inicial: 'G',
    color: '#15803D',
    tags: ['Presencial', 'Salud'],
    lema: 'Cuidar también es una profesión',
    sobreEmpresa: 'GreenLife promueve hábitos saludables con productos y contenido digital.',
    descripcion: 'Apoyarás la atención a pacientes en nuestra sede de Cali.',
    responsabilidades: ['Apoyar la atención a pacientes.', 'Registrar signos vitales.'],
    requisitos: ['Título de auxiliar de enfermería.', 'Disponibilidad de turnos.'],
    beneficios: beneficiosBase,
  },
  {
    id: 8,
    titulo: 'Community Manager',
    empresa: 'PixelLab',
    sectorEmpresa: 'Creatividad y diseño',
    empleados: '1 - 10 empleados',
    categoria: 'ventas',
    ciudad: 'Barranquilla',
    lugar: 'Remoto',
    jornada: 'Tiempo completo',
    contrato: 'Indefinido',
    salarioMin: 1500000,
    salarioMax: 2000000,
    inicial: 'P',
    color: '#6D4FD8',
    tags: ['Remoto', 'Redes sociales'],
    lema: 'Conversaciones que construyen marca',
    sobreEmpresa: 'PixelLab es un estudio creativo que diseña experiencias digitales.',
    descripcion: 'Gestionarás las redes sociales de varios clientes.',
    responsabilidades: ['Planear contenido.', 'Responder a la comunidad.'],
    requisitos: ['Experiencia en redes.', 'Buena redacción.'],
    beneficios: beneficiosBase,
  },
]

// Hoja de vida de ejemplo (mockup 4)
export const cv = {
  nombre: 'Juan David Morales',
  cargo: 'Ingeniero de Sistemas',
  perfil:
    'Apasionado por la tecnología, la innovación y el trabajo en equipo. Busco aportar mis habilidades y conocimientos para crecer profesionalmente y generar un impacto positivo en la organización.',
  contacto: {
    telefono: '+57 300 123 4567',
    correo: 'juandavid.morales@gmail.com',
    ciudad: 'Medellín, Antioquia',
    linkedin: 'linkedin.com/in/juandavidmorales',
  },
  personal: [
    ['Fecha de nacimiento:', '12/05/1998'],
    ['Estado civil:', 'Soltero'],
    ['Cédula:', '1.234.567.890'],
    ['Nacionalidad:', 'Colombiano'],
  ],
  habilidades: [
    'Trabajo en equipo',
    'Resolución de problemas',
    'Pensamiento analítico',
    'Comunicación efectiva',
    'Manejo de herramientas digitales',
    'Adaptabilidad',
  ],
  idiomas: [
    { nombre: 'Español', nivel: 'Nativo', porcentaje: 100 },
    { nombre: 'Inglés', nivel: 'B2', porcentaje: 65 },
  ],
  experiencia: [
    {
      cargo: 'Desarrollador de Software',
      empresa: 'TechSolutions S.A.S.',
      periodo: '2022 – Actualidad',
      logros: [
        'Desarrollo y mantenimiento de aplicaciones web.',
        'Trabajo en equipo con el área de diseño y producto.',
        'Implementación de mejoras en el rendimiento del sistema.',
      ],
    },
    {
      cargo: 'Practicante de Sistemas',
      empresa: 'Innovar S.A.',
      periodo: '2021 – 2022',
      logros: [
        'Soporte técnico a usuarios.',
        'Gestión de bases de datos.',
        'Documentación de procesos y manuales.',
      ],
    },
  ],
  formacion: [
    { titulo: 'Ingeniería de Sistemas', lugar: 'Universidad Nacional de Colombia', periodo: '2016 – 2021' },
    { titulo: 'Bachiller Académico', lugar: 'Colegio San José', periodo: '2010 – 2015' },
  ],
  cursos: [
    'Desarrollo Web Full Stack – Platzi (2023)',
    'Bases de Datos SQL – Coursera (2022)',
    'Introducción a la Inteligencia Artificial – Google (2022)',
  ],
  referencias: [
    { nombre: 'Laura Gómez', rol: 'Jefe Inmediato', lugar: 'TechSolutions S.A.S.', telefono: '+57 300 987 6543' },
    { nombre: 'Carlos Rojas', rol: 'Docente Universitario', lugar: 'Universidad Nacional de Colombia', telefono: '+57 310 456 7890' },
  ],
}

// Formatea un número como pesos: 2500000 -> "$ 2.500.000"
export const pesos = (n) => `$ ${n.toLocaleString('es-CO')}`
